const CustomStyles = {
  transactionHistory: "tw-mx-6",
  header: "tw-flex tw-space-x-2 tw-mt-6 tw-mb-4",
  transaction: "tw-font-bold tw-text-xl tw-pr-2 tw-self-center",
  viewAll: "tw-text-customBlue tw-text-sm tw-self-center",
  orderId: " tw-basis-5/6 tw-text-sm tw-font-bold tw-self-center",
  rightArrow:
    "tw-flex tw-basis-2/6 tw-self-center tw-justify-end tw-h-3  tw-mr-6",
  order: "tw-flex  tw-space-x-2 tw-text-xs tw-font-bold tw-mt-2",
  category: "tw-pr-2 tw-pl-2 tw-rounded-lg tw-bg-customHex",
  status: "tw-bg-black tw-pr-2 tw-pl-2 tw-rounded-lg tw-text-white",
  parcelamount: "tw-flex tw-space-x-6 tw-mt-2 ",
  parcels: "tw-text-sm tw-w-24 tw-h-5 tw-text-customHex1",
  paymentamount: "tw-flex tw-space-x-6 tw-mt-2",
  payment: "tw-text-customHex1 tw-w-24 tw-h-5 tw-text-sm",
  paymentValue: "tw-flex tw-space-x-2 ",
  paymentAmount: "tw-flex tw-space-x-2",
  transactionDate: "tw-flex tw-space-x-6 tw-mt-2",
  date: "tw-text-customHex1 tw-w-24 tw-h-5 tw-text-sm",
  paymentDate: "tw-text-sm",
  orderDate: "tw-flex tw-space-x-14 tw-mt-2",
  orderedOn: "tw-text-customHex1 tw-text-sm",
  orderon: "tw-text-sm",
  estDelivery: "tw-mt-2",
  EstDelivery: "tw-text-customHex1 tw-text-sm",
  EstDate: "tw-flex tw-space-x-20  ",
  deliveryDate: "tw-text-customHex1 tw-text-sm",
  DeliveryDate: "tw-text-sm tw-pl-3",
};
export default CustomStyles;
