#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
npm run test ||
(
        echo '😤Test Cases Failed.!!😤'
        false; 
)

# Check tsconfig standards
npm run lint ||
(
    echo '🤡Are you seriously trying to write that? Make the changes required above.🤡
    false;
)
echo '🤔 Alright.. Code looks good to me... Trying to build now. 🤔'

npm run build ||
(
    echo '❌your build failed ❌👷🔨❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅ You win this time... I am committing this now. ✅✅'